# Generated by Django 4.2.9 on 2024-01-23 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_image_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
